const products = [
    {
        id: 1,
        name: 'iPhone XS',
        description: 'This is iPhone XS',
        type: 'phone',
        capacity: '64',
        price: '500',
        image: 'images/iphone-gold.jpeg',
    },
    {
        id: 2,
        name: 'iPhone 12',
        description: 'This is iPhone 12',
        type: 'phone',
        capacity: '128',
        price: '1000',
        image: 'images/iphone-green.jpeg',
    },
    {
        id: 3,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        type: 'phone',
        capacity: '256',
        price: '1500',
        image: 'images/iphone-black.jpeg',
    },
    {
        id: 4,
        name: 'iPhone 11 Pro Max',
        description: 'This is iPhone 11 Pro Max',
        type: 'phone',
        capacity: '64',
        price: '1000',
        image: 'images/iphone-red.jpeg',
    },
    {
        id: 5,
        name: 'iPhone X ',
        description: 'This is iPhone X',
        type: 'phone',
        capacity: '128',
        price: '2000',
        image: 'images/iphone-silver.jpeg',
    },
    {
        id: 6,
        name: 'iPhone 8 plus',
        description: 'This is iPhone 8 plus',
        type: 'phone',
        capacity: '256',
        price: '1000',
        image: 'images/iphone-blue.jpeg',
    },
]

export default products
